name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login docker regsitry
        run: docker login -u ${{ secrets.DOCKER_USER }} -p  ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v4
      - name: Download aliyun cli
        run: sh download_aliyun_cli.sh
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag zlzforever/aliyun_ddns
      - name: Build the Docker image
        run: docker tag zlzforever/aliyun_ddns zlzforever/aliyun_ddns:1.0
      - name: Publish the Docker image
        run: docker push zlzforever/aliyun_ddns
